/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-slate-800',
    'min-h-screen',
    'p-4',
    'md:p-8',
    'selection:bg-[#FF6B45]',
    'selection:text-white',
    'max-w-4xl',
    'mx-auto',
    'text-slate-200',
    'text-slate-300',
    'text-slate-400',
    'text-slate-500',
    'text-slate-600',
    'text-slate-700',
    'text-slate-900',
    'text-white',
    'bg-slate-900',
    'bg-slate-800',
    'bg-slate-700',
    'bg-slate-600',
    'bg-slate-500',
    'font-sans',
    'shadow-2xl',
    'rounded-xl',
    'rounded-lg',
    'rounded-full',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}; 